# Generated by Django 4.2.2 on 2023-07-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_project_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
