# Generated by Django 4.2.2 on 2023-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_project_is_completed_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
