# Generated by Django 4.2.2 on 2023-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='AmortizationExpenses_1SbfVQw.png', null=True, upload_to=''),
        ),
    ]
