# Generated by Django 4.2.2 on 2023-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/AmortizationExpenses_1SbfVQw.png', null=True, upload_to=''),
        ),
    ]
