# Generated by Django 4.2.2 on 2023-07-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_profile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
    ]
