# Generated by Django 4.2.2 on 2023-07-08 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0014_remove_profile_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
