# Generated by Django 4.2.2 on 2023-07-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_profile_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cropped_image_data',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
