# Generated by Django 4.2.2 on 2023-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_profile_cropped_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cropped_image_data',
            field=models.URLField(blank=True, null=True),
        ),
    ]
