# Generated by Django 4.2.2 on 2023-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_profile_cropped_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('draft', 'Draft'), ('live', 'Live'), ('completed', 'Completed')], default='none', max_length=20),
        ),
    ]
