# Generated by Django 4.2.2 on 2023-07-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('draft', 'Draft'), ('live', 'Live'), ('completed', 'Completed')], default='none', max_length=20),
        ),
    ]
