# Generated by Django 4.2.2 on 2023-07-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_username',
        ),
    ]
