# Generated by Django 4.2.2 on 2023-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_remove_donation_donor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
