# Generated by Django 4.2.2 on 2023-07-16 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_donation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='platform_donation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
