# Generated by Django 4.2.2 on 2023-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_project_city_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_date',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=3, null=True),
        ),
    ]
