# Generated by Django 4.2.2 on 2023-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_project_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('email_sent', 'Email Sent'), ('verified', 'Verified')], default='not_verified', max_length=30),
        ),
    ]
