# Generated by Django 4.2.2 on 2023-07-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='update_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
