# Generated by Django 4.2.2 on 2023-07-25 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_alter_update_update_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_video',
            field=models.FileField(null=True, upload_to='update_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])]),
        ),
    ]
