# Generated by Django 4.2.2 on 2023-07-25 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_alter_update_update_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])]),
        ),
    ]
