# Generated by Django 4.2.2 on 2023-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_updatecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('draft', 'Draft'), ('live', 'Live'), ('funds_withdrawn', 'Funds Withdrawn'), ('completed', 'Completed')], default='none', max_length=20),
        ),
    ]
