# Generated by Django 4.2.2 on 2023-07-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
