# Generated by Django 4.2.2 on 2023-07-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_update_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
