# Generated by Django 4.2.2 on 2023-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cropped_image_data',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
