# Generated by Django 4.2.2 on 2023-07-31 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_alter_profile_cropped_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_video',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])]),
        ),
    ]
