# Generated by Django 4.2.2 on 2023-08-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_alter_project_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
