# Generated by Django 4.2.2 on 2023-08-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_donation_name_alter_donation_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
    ]
