# Generated by Django 4.2.2 on 2023-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_remove_donation_first_name_remove_donation_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
