# Generated by Django 4.2.2 on 2023-08-03 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_donation_first_name_donation_last_name_donation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
