# Generated by Django 4.2.2 on 2023-08-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_donation_donation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='donation_amount',
        ),
    ]
