# Generated by Django 4.2.2 on 2023-08-09 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0053_rename_amount_donation_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='seen_by_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
