# Generated by Django 4.2.2 on 2023-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0054_update_seen_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agree_to_terms',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
