# Generated by Django 4.2.2 on 2023-08-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0055_project_agree_to_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='agree_to_terms',
        ),
    ]
