# Generated by Django 4.2.2 on 2023-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0056_remove_project_agree_to_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('email_sent', 'Email Sent'), ('verified', 'Verified')], default='not_verified', max_length=30),
        ),
    ]
