# Generated by Django 4.2.2 on 2023-09-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0057_remove_project_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='target_date',
        ),
    ]
