# Generated by Django 4.2.2 on 2023-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0058_remove_project_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
