# Generated by Django 4.2.2 on 2023-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0059_project_project_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
