# Generated by Django 4.2.2 on 2023-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0061_alter_project_project_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_qr_code',
        ),
        migrations.AddField(
            model_name='project',
            name='page_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
