# Generated by Django 4.2.2 on 2023-11-19 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0064_alter_withdrawl_withdrawl_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawl',
            name='withdrawl_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='withdrawl',
            name='withdrawl_proof',
            field=models.FileField(blank=True, null=True, upload_to='proof/%y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docxjpg', 'png', 'xls'])]),
        ),
        migrations.AlterField(
            model_name='withdrawl',
            name='withdrawl_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
