# Generated by Django 4.2.2 on 2023-11-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0065_alter_withdrawl_withdrawl_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawl',
            name='withdrawl_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
