# Generated by Django 4.2.2 on 2023-11-19 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0066_alter_withdrawl_withdrawl_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
