# Generated by Django 4.2.2 on 2023-11-24 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0067_project_collaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_number', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Personal', 'Personal'), ('Checking', 'Checking')], default='Personal', max_length=10)),
            ],
        ),
    ]
