# Generated by Django 4.2.2 on 2023-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0068_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(max_length=9),
        ),
    ]
