# Generated by Django 4.2.2 on 2023-12-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0071_alter_bank_routing_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawl',
            name='withdrawl_title',
        ),
        migrations.AddField(
            model_name='withdrawl',
            name='withdrawl_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
