# Generated by Django 4.2.2 on 2023-12-23 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0072_remove_withdrawl_withdrawl_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawl',
            name='withdrawl_proof',
            field=models.FileField(blank=True, null=True, upload_to='proof/%y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
