# Generated by Django 4.2.2 on 2023-12-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0074_remove_withdrawl_id_alter_withdrawl_withdrawl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawl',
            name='withdrawl_proof',
            field=models.FileField(blank=True, null=True, upload_to='proof/%y'),
        ),
    ]
